title: Web Developement Bootcamp Blog
author: M Eller
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Web Developement Bootcamp Blog

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
